name: AnotherWorldPlugin
version: 1.0
main: fr.thybax.anotherworldplugin.Main
api-version: 1.19
authors: [ Thybax ]
description: Plugin pour AnotherWorld
commands:

  giveitem:
    description: Give Custom Item.
    permission: giveitem.use
    permission-message: Vous n'avez pas la permission d'effectuer cette commande

  trade:
    description: Commande pour trade
    permission: trade.use

  money:
    description: Permet de verifier son argent (/money <type>)

  pay:
    description: Permet d'envoyer de l'argent a quelqu'un (/pay <player> <type> <somme>)

  cheque:
    description: Permet de créer un cheque de n'importe quelle monnaie

  giveeco:
    description: /!\ Commande Admin /!\ Permet de give n'importe quelle monnaie
    permission: giveeco.use
    permission-message: Vous n'avez pas la permission d'effectuer cette commande

  withdraweco:
    description: /!\ Commande Admin /!\ Permet d'enlever une certaine somme
    permission: withdraweco.use
    permission-message: Vous n'avez pas la permission d'effectuer cette commande

  anotherReload:
    description: /!\ Commande Admin /!\ Permet de reload le configFile
    permission: withdraweco.use
    permission-message: Vous n'avez pas la permission d'effectuer cette commande

  shop:
    description: Permet d'ouvrir le /shop

  auctionhouse:
    description: Permet d'ouvrir l'hotel des ventes
    permission: auctionhouse.use
    aliases: ah